name: Output information
on: [workflow_dispatch]
jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - name: output github context
              run: echo "${{ toJson(github) }}"

            - name: show date
              run: date
            
            - name: show node version
              run: node -v